# Filename: Dockerfile_mkl

# make this global 
ARG LIB_INSTALL
ARG LIB_INSTALL2


FROM ubuntu:18.04 AS builder

ARG BOOST_IO
ARG LIB_INSTALL
ARG STATIC
ARG CMAKE_VERSION_MAJOR=3.13
ARG CMAKE_VERSION_MINOR=0
ARG HTSLIB_VERSION=1.18

WORKDIR /src

ADD http://cmake.org/files/v${CMAKE_VERSION_MAJOR}/cmake-${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}-Linux-x86_64.sh cmake_install.sh
ADD http://code.enkre.net/bgen/tarball/release/v1.1.7 v1.1.7.tgz
ADD https://github.com/samtools/htslib/releases/download/$HTSLIB_VERSION/htslib-$HTSLIB_VERSION.tar.bz2 htslib-$HTSLIB_VERSION.tar.bz2

# install BGEN and HTSlib libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
      gcc \
      g++ \
      libz-dev \
      libbz2-dev \
      liblzma-dev \
      libcurl4-openssl-dev \
      libssl-dev \
      make \
      gnupg \
      python3 \
      gfortran \
      zlib1g-dev \
      apt-transport-https ca-certificates \
      $LIB_INSTALL \
      && tar -xf htslib-$HTSLIB_VERSION.tar.bz2 \
      && cd htslib-$HTSLIB_VERSION/ \
      && ./configure \
      && make \
      && make install \
      && cd .. \
      && sh cmake_install.sh --prefix=/usr/local --skip-license --exclude-subdir \
      && rm cmake_install.sh \
      && tar -xzf v1.1.7.tgz \
      && rm v1.1.7.tgz \
      && cd v1.1.7 \
      && python3 waf configure \
      && python3 waf

# install MKL library (from 
ADD https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB intel_key.PUB
RUN apt-key add intel_key.PUB \
      && sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' \
      && apt-get update \
      && apt-get install intel-mkl-64bit-2018.2-046 -y --no-install-recommends \
      && echo "MKL_THREADING_LAYER=GNU" >> /etc/environment

COPY . /src/regenie

WORKDIR /src/regenie

# compile with MKL as static
RUN BGEN_PATH=/src/v1.1.7 HAS_BOOST_IOSTREAM=$BOOST_IO MKLROOT=/opt/intel/mkl/ HTSLIB_PATH=/usr/local/lib/ STATIC=1 cmake . \
      && make

# no need to install Boost IO and MKL here (static linking)
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
      libgomp1 gfortran \
      libz-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev \
      && rm -rf /var/lib/apt/lists/*

COPY --from=builder /src/regenie/regenie /usr/local/bin

