# Filename: Dockerfile_mkl

# make this global
ARG LIB_INSTALL
ARG LIB_INSTALL2


FROM ubuntu:18.04 AS builder

ARG BOOST_IO=0
ARG LIB_INSTALL
ARG SHARED=0
ARG CMAKE_VER=3.17.5
ARG BGEN_PATH=/src/v1.1.7
ARG SRC_DIR=/src/regenie
ARG CPU_COUNT=1
ARG MKLROOT=/opt/intel/mkl/
ARG VERBOSE=1

WORKDIR /src

ADD http://code.enkre.net/bgen/tarball/release/v1.1.7 v1.1.7.tgz
ADD https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/cmake-${CMAKE_VER}-Linux-x86_64.sh cmake.sh

# install BGEN library
RUN apt-get update && apt-get install -y --no-install-recommends \
      g++ \
      make \
      gnupg \
      python3 \
      zlib1g-dev \
      libeigen3-dev \
      apt-transport-https ca-certificates \
      $LIB_INSTALL \
      && bash cmake.sh --prefix=/usr/local --skip-license \
      && rm cmake.sh \
      && tar -xzf v1.1.7.tgz \
      && rm v1.1.7.tgz \
      && cd v1.1.7 \
      && python3 waf configure \
      && python3 waf

# install MKL library (from
ADD https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB intel_key.PUB
RUN apt-key add intel_key.PUB \
      && sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' \
      && apt-get update \
      && apt-get install intel-mkl-64bit-2018.2-046 -y --no-install-recommends \
      && echo "MKL_THREADING_LAYER=GNU" >> /etc/environment

COPY . /src/regenie

WORKDIR /src/regenie

# compile with MKL as static
RUN cmake \
      -DBUILD_SHARED_LIBS:BOOL="${SHARED}" \
      -DCMAKE_PREFIX_PATH:PATH=/usr/local \
      -DCMAKE_INSTALL_PREFIX:PATH=/usr/local \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DCMAKE_BUILD_TYPE="Release" \
      -DBGEN_PATH="${BGEN_PATH}" \
      -DHAS_BOOST_IOSTREAM:BOOL="${BOOST_IO}" \
      -DWITH_MKL:BOOL=ON \
      -DWITH_OPENBLAS:BOOL=OFF \
      -S "${SRC_DIR}" \
    && make VERBOSE=${VERBOSE} -j${CPU_COUNT} regenie \
    && make install


# no need to install Boost IO and MKL here (static linking)
FROM ubuntu:18.04
ARG LIB_INSTALL2

RUN apt-get update && apt-get install -y --no-install-recommends \
      libgomp1 $LIB_INSTALL2 \
      && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/regenie /usr/local/bin
