name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: docker.pkg.github.com
  REPO_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    steps:      
    - 
      name: Checkout repository
      uses: actions/checkout@v2

    - 
      name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"
    
    - name: Build and push image to Docker
      run: |
        IMAGE_NAME="docker.pkg.github.com/${{ env.REPO_NAME }}/regenie:v${{ steps.getversion.outputs.version }}.gz"
        echo "${{ secrets.GH_PAT }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker build -f Dockerfile_mkl \
          --build-arg BOOST_IO=1 \
          --build-arg LIB_INSTALL=libboost-iostreams-dev \
          -t $IMAGE_NAME . 
        docker push $IMAGE_NAME
